import { JSDOM } from 'jsdom';
import fs from 'fs';
const story = JSON.parse(fs.readFileSync('content/story.json','utf8'));
const dom = new JSDOM('<!DOCTYPE html><html><body><div id="arg-root"></div></body></html>',{url:'http://localhost:8090/',runScripts:'dangerously',pretendToBeVisual:true});
const { window } = dom;
window.eval(fs.readFileSync('engine/arg-runtime.js','utf8'));
window.ARG_STORY = story; window.ARG.boot();
const nav=h=>{window.location.hash=h;window.dispatchEvent(new window.HashChangeEvent('hashchange'));};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
window.localStorage.removeItem('arg-rivervalley-v2');
window.ARG.boot(); await wait(20);
const clickKw=l=>[...window.document.querySelectorAll('.kw-inline')].find(w=>w.textContent.includes(l))?.click();
const link=t=>[...window.document.querySelectorAll('.link-item a')].find(a=>a.textContent.includes(t));
const contact=t=>[...window.document.querySelectorAll('.contact-item')].find(x=>x.textContent.includes(t));
const chatBtn=t=>[...window.document.querySelectorAll('.chat-choice .btn')].find(b=>b.textContent.includes(t));
const chips=()=>[...window.document.querySelectorAll('.combo-chip')];
const clues=()=>JSON.parse(window.localStorage.getItem('arg-rivervalley-v2')).clues;
nav('#/page/n_room');await wait(20);
clickKw('钥匙');await wait(20);
link('让罗伦萨进入河谷疗养院').click();await wait(20);
clickKw('鞋印');clickKw('合照');clickKw('书');clickKw('通讯终端');clickKw('尸体的状态');await wait(20);
nav('#/page/n_lls_chat');await wait(20);
const ask=async t=>{const i=window.document.querySelector('.chat-input');i.value=t;[...window.document.querySelectorAll('.chat-input-row .btn')].pop().click();await wait(20);};
await ask('现场情况');await ask('鞋印');await ask('合照上的女人');await ask('理事会');
nav('#/page/n_index');await wait(20);
link('打开理事会档案库').click();await wait(20);
link('T-001').click();await wait(20);
clickKw('抹除的名字');await wait(20);
nav('#/page/n_zhuizhi');await wait(20);
clickKw('木巳的批注');clickKw('样本编号');await wait(20);
nav('#/page/n_desktop');await wait(20);
chips().find(c=>c.textContent.includes('抹除的代号')).click();
chips().find(c=>c.textContent.includes('合照')).click();
window.document.querySelector('.combo-btn').click();await wait(20);
nav('#/page/n_login');await wait(20);
const input=window.document.querySelector('.pwd-input');
input.value='ST17-0415';window.document.querySelector('.login-box .btn').click();await wait(20);
nav('#/page/n_lls_chat');await wait(20);
await ask('通讯记录');
nav('#/page/n_contacts');await wait(20);
contact('威胁短信').click();await wait(20);chatBtn('回复记录').click();
contact('已删除的会话').click();await wait(20);chatBtn('缓存残片').click();
contact('陌生号码').click();await wait(20);chatBtn('追溯号码').click();
contact('黑泽医院').click();await wait(20);chatBtn('翻查历史账单').click();chatBtn('收件人一栏').click();
contact('南曲').click();await wait(20);chatBtn('南曲相关的档案').click();await wait(20);
nav('#/page/n_desktop');await wait(20);
chips().find(c=>c.textContent.includes('批注')).click();
chips().find(c=>c.textContent.includes('南曲')).click();
window.document.querySelector('.combo-btn').click();await wait(20);
chips().find(c=>c.textContent.includes('钥匙')).click();
chips().find(c=>c.textContent.includes('鞋印')).click();
window.document.querySelector('.combo-btn').click();await wait(20);
console.log('rush clues:', clues().length, '(expect 20)');
nav('#/page/n_contacts');await wait(20);
const c=contact('罗伦萨');
console.log('contact found:',!!c);
c.click();await wait(20);
chatBtn('翻看与罗伦萨').click(); await wait(20);
chatBtn('再试一次').click(); await wait(20);
chatBtn('南曲的档案里').click(); await wait(20);
chatBtn('汇报').click(); await wait(20);
nav('#/page/n_final_chat'); await wait(20);
const teinBtn = [...window.document.querySelectorAll('.verdict-btn')].find(b => b.textContent.includes('指认特因'));
if (!teinBtn) { console.log('low-progress end1 reachable: false (no verdict button)'); process.exit(1); }
teinBtn.click(); await wait(20);
const ok = window.location.hash === '#/page/n_end1' && window.document.body.textContent.includes('净化');
console.log('low-progress end1 reachable:', ok);
process.exit(ok ? 0 : 1);
